package wolox.training.exceptions;

public class UsernameExistsException extends RuntimeException {

    public UsernameExistsException(Throwable cause) {
        super(cause);
    }
}
